# Build matrix configurations
---
include:
  # Aurora Sweep
  # - board: nice_nano_v2
  #   shield: splitkb_aurora_sweep_left nice_view_adapter nice_view
  #   artifact-name: sweep-left
  # - board: nice_nano_v2
  #   shield: splitkb_aurora_sweep_right nice_view_adapter nice_view
  #   artifact-name: sweep-right

  # Totem with OLED dongle
  # - board: seeeduino_xiao_ble
  #   shield: totem_dongle dongle_display
  #   artifact-name: totem-dongle
  # - board: seeeduino_xiao_ble
  #   shield: totem_left
  #   artifact-name: totem-left
  # - board: seeeduino_xiao_ble
  #   shield: totem_right
  #   artifact-name: totem-right

  # Kyria rev 3.1 with Seeed Stutio Round Display dongle
  - board: seeeduino_xiao_ble
    shield: trikyria_dongle seeed_round_display
    artifact-name: kyria-dongle
  - board: seeeduino_xiao_ble
    shield: trikyria_dongle_oled dongle_display
    artifact-name: kyria-dongle-oled
  - board: nice_nano_v2
    shield: trikyria_left
    artifact-name: kyria-left
  - board: nice_nano_v2
    shield: trikyria_right
    artifact-name: kyria-right

  # Settings Reset
  # - board: nice_nano_v2
  #   shield: settings_reset
  #   artifact-name: nano-reset
  # - board: seeeduino_xiao_ble
  #   shield: settings_reset
  #   artifact-name: xiao-reset
