# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # Aurora Sweep
  - board: nice_nano_v2
    shield: splitkb_aurora_sweep_left nice_view_adapter nice_view
    artifact-name: sweep_left
  - board: nice_nano_v2
    shield: splitkb_aurora_sweep_right nice_view_adapter nice_view
    artifact-name: sweep_right

  # Totem
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_display
    artifact-name: totem_dongle
  - board: seeeduino_xiao_ble
    shield: totem_left
    artifact-name: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
    artifact-name: totem_right

  # Settings Reset
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
