manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ctranstrum
      url-base: https://github.com/ctranstrum
    - name: caksoylar
      url-base: https://github.com/caksoylar
    # - name: englmaxi
    #   url-base: https://github.com/englmaxi

  projects:
    - name: zmk
      remote: zmkfirmware
      # The revision needs to match in .github/workflows/build.yml
      revision: v0.3
      import: app/west.yml
    - name: chuck
      remote: ctranstrum
      revision: zmk
    # - name: lintilla
    #   remote: ctranstrum
    #   revision: zmk
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    # - name: zmk-dongle-display
    #   remote: englmaxi
    #   revision: main

  self:
    path: config
