manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: rgb
      url-base: https://github.com/muriworks
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      # remote: rgb
      # revision: feature/animations
      import: app/west.yml
  self:
    path: config
