manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ctranstrum
      url-base: https://github.com/ctranstrum
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: lintilla
      remote: ctranstrum
      revision: zmk
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
  self:
    path: config
