manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: gc9a01a_zephyr_driver
      description: Seeed Round Display out-of-tree driver
      remote: petejohanson
      revision: main
  self:
    path: config
